{% set version = '2.0.0' %}
{% set name = "beyondcell" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-beyondcell
  version: {{ version }}

source:
  git_url: /home/sagarcia/Documents/bu_repositories/beyondcell
#   git_tag: v{{ version }}

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

build_platform:
  osx_arm64: osx_64

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base >=4.0.0
    - r-cowplot >=1.1.0
    - r-dmwr >=0.4.1
    - r-ggrepel >=0.8.2
    - r-patchwork >=1.0.1
    - r-rcolorbrewer >=1.1-2
    - r-scales >=1.1.1
    - r-see
    - r-tidyverse >=1.3.2
    - r-Seurat >=4.0.0
    - r-viridis >=0.5.1
    - umap-learn

  run:
    - r-base >=4.0.0
    - r-cowplot >=1.1.0
    - r-dmwr >=0.4.1
    - r-ggrepel >=0.8.2
    - r-patchwork >=1.0.1
    - r-rcolorbrewer >=1.1-2
    - r-scales >=1.1.1
    - r-see
    - r-tidyverse >=1.3.2
    - r-Seurat >=4.0.0
    - r-viridis >=0.5.1
    - umap-learn
    
test:
  commands:
    - $R -e "library(\"{{ name }}\")"           # [not win]
    - "\"%R%\" -e \"library(\"{{ name }}\")\""  # [win]

about:
  home: https://github.com/cnio-bu/beyondcell
  license: GPL-3
  summary: Beyondcell is a methodology for the identification of drug vulnerabilities 
    in single cell RNA-seq data. To this end, Beyondcell focuses on the analysis of drug-related 
    commonalities between cells by classifying them into distinct therapeutic clusters.
  license_file:
    - LICENSE
