image: condaforge/mambaforge:latest

before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - mamba info -a
  - mamba install boa
  
conda_build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - cd .tests/
    - bash build_conda_package.sh ${PYTHON_VERSION}
